blueprint:
  name: Send time to thermostats once a day.
  description: Send time to thermostat at 1:00 AM as a timestamp. 
  domain: automation
  source_url: https://github.com/claudegel/sinope-zha/tree/master/automation/blueprints/send_time_to_thermostats.yaml
  input:
    climate_target:
      name: Thermostat_ieee
      description: Target thermostat entity. Can put more then one.
      selector:
        target:
          entity:
            domain: climate

# Once a day send time to thermostats to keep them accurate.
mode: single

triggers:
  - trigger: time
    at: "01:00:00"

variables:
  thermostats:
    - !input climate_target

condition: []

action:
  - repeat:
      count: "{{thermostats|length}}"
      sequence:
        - action: zha.set_zigbee_cluster_attribute
          data:
            cluster_type: in
            ieee: "{{ thermostats[repeat.index-1] }}"
            endpoint_id: 1
            cluster_id: 0xff01
            attribute: 0x0020
            value: "{{ (as_timestamp(utcnow()) - as_timestamp('2000-01-01'))| int }}"
