blueprint:
  name: thermostat icon update via Environement Canada weather conditions codes.
  description: Change thermostat icon when weather condition code changes. Your Environment Canada icon code source should be set to your_city_icon_code.
  domain: automation
  source_url: https://github.com/claudegel/sinope-zha/tree/master/automation/blueprints/update_icon_env_canada.yaml
  input:
    weather_entity:
      name: Your City Weather Icon Code source
      description: Entity ID of the weather icon code sensor
      selector:
        entity:
          domain: sensor
    climate_target:
      name: Thermostat_ieee
      description: Target thermostat entity
      selector:
        target:
          entity:
            domain: climate

# If weather code change we update the thermostat,
mode: single

triggers:
  - trigger: state
    entity_id: !input weather_entity

variables:
  weather_change:
    "00": Sun
    "01": Sun2
    "02": Cloudsun
    "03": Cloudsun2
    "06": Cloudrainsun
    "07": Cloudlightning2
    "08": Cloudsnow2
    "10": Cloud2
    "11": Cloudrain2
    "12": Cloudrain3
    "13": Cloudrain
    "14": Cloudsnow
    "15": Cloudsnow
    "16": Cloudsnow4
    "17": Cloudsnow3
    "18": Cloudsnow3
    "19": Cloudlightning
    "23": Cloudfog
    "24": Cloudfog
    "25": Cloudsnow5
    "26": Cloudsnow3
    "27": Cloud
    "28": Cloud3
    "30": Moonstar
    "31": Cloudmoon
    "32": Cloudmoon2
    "33": Cloudmoon3
    "36": Cloudrainmoon
    "37": Cloudrainmoon3
    "38": Cloudsnow6
    "39": Cloudrainmoon2
    "40": Cloudsnow5
    "41": Cloudfog
    "42": Cloudfog
    "44": Cloudfog
    "45": Cloudfog
    "46": Cloudlightning
    "47": Cloudlightning
    "48": Cloudrain

  thermostats:
    - !input climate_target

actions:
  - repeat:
      count: "{{thermostats|length}}"
      sequence:
        - action: zha.set_zigbee_cluster_attribute
          data:
            cluster_type: in
            ieee: "{{ thermostats[repeat.index-1] }}"
            endpoint_id: 1
            cluster_id: 0xff01
            attribute: 0x0013
            value: "{{ weather_change.get(states(weather_entity), 'Hide') }}"
