blueprint:
  name: thermostat icon update via Openweathermap weather conditions codes, night time period.
  description: Change thermostat icon when weather condition code changes. Your Openweathermap icon code source should be set correctly for your location. You need one automation for day time and one for night time. You also need to install integration sun.
  domain: automation
  source_url: https://github.com/claudegel/sinope-zha/tree/master/automation/blueprints/update_icon_openweathermap_night.yaml
  input:
    weather_entity:
      name: Your City Weather Icon Code source
      description: Entity ID of the weather icon code sensor
      selector:
        entity:
          domain: sensor
    climate_target:
      name: Thermostat_ieee
      description: Target thermostat entity
      selector:
        target:
          entity:
            domain: climate

# If weather code change we update the thermostat,
mode: single

triggers:
  - trigger: state
    entity_id: !input weather_entity
  - trigger: sun
    event: sunset

variables:
  weather_change:
    "200": Cloudrainmoon2
    "201": Cloudrainmoon2
    "211": Cloudrainmoon2
    "212": Cloudrainmoon2
    "300": Cloud3
    "301": Cloud3
    "311": Cloud3
    "500": Cloudrainmoon
    "501": Cloudrainmoon4
    "502": Cloudrainmoon5
    "503": Cloudrainmoon5
    "504": Cloudrain3
    "511": Cloudrainmoon3
    "521": Cloudrain2
    "522": Cloudrain3
    "600": Cloudsnow6
    "601": Cloudsnow4
    "602": Cloudsnow3
    "613": Cloud
    "620": Cloudsnow5
    "621": Cloudsnow3
    "622": Cloudsnow5
    "701": Cloudfog
    "711": Cloudfog
    "721": Cloudfog
    "731": Cloudfog
    "741": Cloudfog
    "751": Cloudfog
    "761": Cloudfog
    "771": Cloudsnow5
    "800": Moonstar
    "801": Cloudmoon
    "802": Cloudmoon2
    "803": Cloudmoon3
    "804": Cloud2

  thermostats:
    - !input climate_target

conditions:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"

actions:
  - repeat:
      count: "{{ thermostats.entity_id | count }}"
      sequence:
        - action: zha.set_zigbee_cluster_attribute
          data:
            cluster_type: in
            ieee: "{{ thermostats.entity_id[repeat.index-1] }}"
            endpoint_id: 1
            cluster_id: 0xff01
            attribute: 0x0013
            value: "{{ weather_change.get(states(weather_entity), 'Hide') }}"
 
